/**
 * Photos des réalisations.
 *
 * Pour ajouter une photo :
 *  1. déposez le fichier (idéalement .webp ou .jpg, ~1600 px de large) dans public/images/realisations/
 *  2. ajoutez une entrée ci-dessous.
 *
 * Le texte « alt » est important pour Google Images : décrivez précisément la photo
 * (type de travaux + ville), par ex. « Mur de clôture en parpaing enduit à Joué-lès-Tours ».
 */
export type ServiceName = 'Maçonnerie' | 'Terrassement' | 'Ravalement de façade' | 'Carrelage'

export interface Realisation {
  src: string
  alt: string
  title: string
  description: string
  services: ServiceName[]
  /** Commune du chantier (optionnel, mais très utile pour le référencement local) */
  city?: string
  width: number
  height: number
}

export const realisations: Realisation[] = [
  {
    src: '/images/realisations/terrasse-travertin-sur-dalle-beton-avant-apres.webp',
    alt: 'Avant / après d\'une terrasse : dalle béton coulée puis habillée de travertin posé en opus romain',
    title: 'Terrasse en travertin sur dalle béton',
    description: 'Coulage d\'une grande dalle béton coffrée, puis pose d\'un dallage en travertin en opus romain : une terrasse lumineuse et durable au pied de la maison.',
    services: ['Carrelage', 'Maçonnerie'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/maison-neuve-enduit-parement-pierre-avant-apres.webp',
    alt: 'Avant / après d\'une maison neuve en brique : façade enduite avec encadrements et parement effet pierre',
    title: 'Maison neuve : enduit et parement pierre',
    description: 'Maison neuve livrée en brique : enduit de façade, encadrements des ouvertures, chaînes d\'angle et parement effet pierre autour de l\'entrée.',
    services: ['Ravalement de façade'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/extension-maison-parpaing-etapes.webp',
    alt: 'Étapes de construction d\'une extension en parpaing : soubassement, dalle, murs et pignon',
    title: 'Extension de maison, du soubassement au pignon',
    description: 'Suivi complet d\'une extension accolée à une maison : soubassement et hérisson, dalle, élévation des murs en parpaing puis montée du pignon.',
    services: ['Maçonnerie', 'Terrassement'],
    width: 1200,
    height: 1200,
  },
  {
    src: '/images/realisations/rampe-garage-murs-soutenement-etapes.webp',
    alt: 'Terrassement d\'une rampe d\'accès au garage en sous-sol, fondations puis murs de soutènement en blocs',
    title: 'Rampe de garage et murs de soutènement',
    description: 'Décaissement de l\'accès au garage en sous-sol, coulage des fondations puis construction de deux murs de soutènement en blocs à bancher.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 1000,
    height: 1000,
  },
  {
    src: '/images/realisations/facade-baies-decor-pierre-avant-apres.webp',
    alt: 'Avant / après d\'une façade en parpaing avec deux baies vitrées, transformée en enduit décor pierre',
    title: 'Façade en enduit décor pierre',
    description: 'Mur en parpaing brut protégé sous échafaudage, puis enduit décor pierre sculpté avec encadrements autour des deux baies vitrées.',
    services: ['Ravalement de façade'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/mur-cloture-enduit-piliers-avant-apres.webp',
    alt: 'Avant / après d\'un mur de clôture sur rue : parpaing brut puis mur enduit avec piliers et chaperons',
    title: 'Mur de clôture enduit avec piliers',
    description: 'Reprise d\'un mur de clôture sur rue : montage des piliers, enduit de finition et pose des chaperons pour un ensemble net et durable.',
    services: ['Maçonnerie', 'Ravalement de façade'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/cour-beton-joints-decoratifs-avant-apres.webp',
    alt: 'Avant / après d\'une cour : bordures en pavés posées en diagonale puis béton coulé devant la maison',
    title: 'Cour béton avec joints décoratifs',
    description: 'Préparation du terrain, pose de bordures en pavés formant un motif en diagonale, puis coulage de la cour et de l\'accès garage en béton.',
    services: ['Maçonnerie', 'Terrassement'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/allee-gravier-blanc-bordures-avant-apres.webp',
    alt: 'Avant / après d\'une allée : terrain décaissé puis allée en gravier blanc avec bordures béton',
    title: 'Allée en gravier blanc et bordures',
    description: 'Décaissement et nivellement de l\'allée, pose de bordures le long de la pelouse puis mise en place d\'un gravier blanc concassé.',
    services: ['Terrassement'],
    width: 1000,
    height: 1000,
  },
  {
    src: '/images/realisations/ravalement-facade-enduit-decor-pierre-avant-apres.webp',
    alt: 'Avant / après du ravalement d\'une maison : façade blanche transformée en enduit décor pierre avec encadrements',
    title: 'Ravalement en enduit décor pierre',
    description: 'Transformation complète d\'une façade enduite en façade décor pierre, avec chaînes d\'angle et encadrements des ouvertures et du garage.',
    services: ['Ravalement de façade'],
    width: 1080,
    height: 1080,
  },
  {
    src: '/images/realisations/ravalement-maison-de-ville-enduit-pierre-avant-apres.webp',
    alt: 'Avant / après du ravalement d\'une maison de ville : façade rose dégradée refaite en enduit décor pierre',
    title: 'Rénovation de façade d\'une maison de ville',
    description: 'Façade abîmée et décollée : préparation du support sous échafaudage puis enduit décor pierre avec encadrements de fenêtres et de porte.',
    services: ['Ravalement de façade'],
    width: 1366,
    height: 1200,
  },
  {
    src: '/images/realisations/escalier-beton-helicoidal-coffrage-coulage.webp',
    alt: 'Escalier tournant en béton : coffrage bois et ferraillage, puis marches coulées',
    title: 'Escalier béton coulé sur place',
    description: 'Réalisation d\'un escalier tournant en béton armé : coffrage bois sur mesure, ferraillage des marches puis coulage en place.',
    services: ['Maçonnerie'],
    width: 1100,
    height: 1100,
  },
  {
    src: '/images/realisations/mur-cloture-maison-neuve-etapes.webp',
    alt: 'Construction d\'un mur de clôture sur rue : cour ouverte, fondation coulée puis murs et piliers en parpaing',
    title: 'Mur de clôture d’une maison neuve',
    description: 'Ouverture de la tranchée à la mini-pelle, coulage de la semelle filante, puis montage des murs et des piliers du portail en parpaing.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 1000,
    height: 1000,
  },
  {
    src: '/images/realisations/portail-cintre-enduit-decor-pierre.webp',
    alt: 'Mur d\'enceinte avec porche cintré en enduit décor pierre et pilastres en pierre de taille',
    title: 'Portail cintré en enduit décor pierre',
    description: 'Mur d\'enceinte et porche cintré habillés d\'un enduit décor pierre, avec pilastres et encadrements façon pierre de taille.',
    services: ['Ravalement de façade', 'Maçonnerie'],
    width: 922,
    height: 516,
  },
  {
    src: '/images/realisations/fondations-mur-cloture-ferraillage-coulage.webp',
    alt: 'Fondations d\'un mur de clôture : tranchée terrassée avec ferraillage, puis semelle béton coulée avec attentes',
    title: 'Fondations d\'un mur de clôture',
    description: 'Ouverture de la tranchée, pose du ferraillage de la semelle filante puis coulage du béton avec les attentes du futur mur.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 1000,
    height: 805,
  },
  {
    src: '/images/realisations/dalle-beton-mur-pierre-ferraillage-coulage.webp',
    alt: 'Dalle béton au pied d\'un mur en pierre : coffrage et treillis soudé, puis béton coulé',
    title: 'Dalle béton au pied d’un mur ancien',
    description: 'Terrassement, coffrage bois et treillis soudé, puis coulage d\'une dalle béton au pied d\'un mur ancien en pierre.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 1000,
    height: 1000,
  },
  {
    src: '/images/realisations/couloir-parement-pierre-avant-apres.webp',
    alt: 'Avant / après d\'un couloir : murs blancs habillés de parement en pierre naturelle',
    title: 'Couloir habillé de parement pierre',
    description: 'Habillage des murs d\'un couloir en parement pierre : un intérieur chaleureux au cachet de maison de caractère, en harmonie avec le sol en travertin.',
    services: ['Maçonnerie'],
    width: 1366,
    height: 1000,
  },
  {
    src: '/images/realisations/preau-facade-enduit-decor-pierre.webp',
    alt: 'Façade et poteaux de préau en enduit décor pierre avec pierres colorées',
    title: 'Préau et façade en décor pierre',
    description: 'Façade et poteaux du préau habillés d\'un enduit décor pierre, avec encadrements des menuiseries et pierres de couleur.',
    services: ['Ravalement de façade'],
    width: 922,
    height: 516,
  },
  {
    src: '/images/realisations/extension-enduit-decor-pierre-baies.webp',
    alt: 'Extension de maison avec grandes baies, façade en enduit décor pierre et encadrements',
    title: 'Extension en enduit décor pierre',
    description: 'Extension vitrée habillée d\'un enduit décor pierre, avec encadrements lisses autour des baies et chaînes d\'angle.',
    services: ['Ravalement de façade'],
    width: 619,
    height: 1100,
  },
  {
    src: '/images/realisations/terrasse-travertin-opus-vue-ensemble.webp',
    alt: 'Grande terrasse en dallage travertin posé en opus romain le long d\'une maison',
    title: 'Terrasse travertin, vue d’ensemble',
    description: 'Vue d\'ensemble de la terrasse : dallage en travertin posé en opus romain, joints réguliers et raccord soigné au pied de la façade.',
    services: ['Carrelage'],
    width: 1400,
    height: 1050,
  },
  {
    src: '/images/realisations/seuil-travertin-caniveau-grille.webp',
    alt: 'Seuil de porte en dallage travertin avec caniveau à grille intégré',
    title: 'Seuil en travertin et caniveau',
    description: 'Détail de finition : dallage en travertin devant la porte de service, avec caniveau à grille intégré pour l\'évacuation des eaux.',
    services: ['Carrelage'],
    width: 825,
    height: 1100,
  },
  {
    src: '/images/realisations/facade-maison-de-ville-enduit-encadrements.webp',
    alt: 'Façade de maison de ville enduite avec encadrements de fenêtres et chaînes d\'angle',
    title: 'Ravalement d’une maison de ville',
    description: 'Ravalement d\'une façade de maison de ville : enduit de finition, encadrements des ouvertures et chaînes d\'angle en relief.',
    services: ['Ravalement de façade'],
    width: 922,
    height: 516,
  },
  {
    src: '/images/realisations/pignon-enduit-encadrement-porte-pierre.webp',
    alt: 'Pignon enduit avec encadrement de porte en décor pierre',
    title: 'Pignon enduit et encadrement de porte',
    description: 'Enduit d\'un pignon et création d\'un encadrement de porte en décor pierre, harmonisé avec les fenêtres.',
    services: ['Ravalement de façade'],
    width: 621,
    height: 1100,
  },
  {
    src: '/images/realisations/facade-enduit-decor-pierre-pignon-dalle-beton.webp',
    alt: 'Pignon en enduit décor pierre avec médaillon fleur de lys, encadrements des ouvertures et dalle béton',
    title: 'Façade décor pierre, pignon et dalle béton',
    description: 'Enduit taloché, pignon décor pierre avec médaillon fleur de lys, chaînes d\'angle, encadrements d\'ouvertures et coulage de la dalle béton.',
    services: ['Maçonnerie', 'Ravalement de façade'],
    width: 942,
    height: 1256,
  },
  {
    src: '/images/realisations/terrassement-allee-enrobe-maison-neuve.webp',
    alt: 'Terrassement et création d\'une allée en enrobé avec bordures devant une maison neuve',
    title: 'Terrassement et allée en enrobé',
    description: 'Terrassement à la pelle mécanique, pose de bordures, préparation de la couche de forme puis réalisation d\'une allée en enrobé.',
    services: ['Terrassement'],
    width: 1080,
    height: 1080,
  },
  {
    src: '/images/realisations/bande-gravier-blanc-tour-maison.webp',
    alt: 'Bande de gravier blanc le long d\'une façade, entre la maison et la pelouse',
    title: 'Bande de gravier au pied de la maison',
    description: 'Décaissement le long de la façade et mise en place d\'une bande de gravier blanc qui protège le pied de mur et facilite l\'entretien.',
    services: ['Terrassement'],
    width: 825,
    height: 1100,
  },
  {
    src: '/images/realisations/extension-maison-gros-oeuvre-parpaing.webp',
    alt: 'Extension de maison en parpaing accolée à une maison en pierre : gros œuvre avec pignon, linteaux et dalle',
    title: 'Extension de maison – gros œuvre',
    description: 'Construction d\'une extension accolée à une maison ancienne en pierre : dalle, élévation des murs en parpaing, pignon, linteaux et grandes ouvertures.',
    services: ['Maçonnerie'],
    width: 1200,
    height: 1600,
  },
  {
    src: '/images/realisations/gros-oeuvre-parpaing-linteaux-etais.webp',
    alt: 'Gros œuvre en parpaing d\'une annexe avec grandes ouvertures, linteaux et étais',
    title: 'Gros œuvre : murs, linteaux et étais',
    description: 'Élévation des murs en parpaing d\'une annexe, avec grandes ouvertures soutenues par des étais le temps de la prise des linteaux.',
    services: ['Maçonnerie'],
    width: 1106,
    height: 658,
  },
  {
    src: '/images/realisations/mur-parpaing-elevation-chainage.webp',
    alt: 'Mur en parpaing en cours d\'élévation avec coffrage et ferraillage du chaînage horizontal',
    title: 'Mur en parpaing et chaînage',
    description: 'Élévation d\'un mur en blocs béton, coffrage et ferraillage du chaînage en tête de mur avant coulage.',
    services: ['Maçonnerie'],
    width: 1152,
    height: 2048,
  },
  {
    src: '/images/realisations/mur-cloture-parpaing-raidisseurs.webp',
    alt: 'Long mur de clôture en parpaing avec raidisseurs, protégé avant enduit',
    title: 'Mur de clôture en parpaing',
    description: 'Construction d\'un long mur de clôture en parpaing avec raidisseurs béton, protégé par bâche avant la phase d\'enduit.',
    services: ['Maçonnerie'],
    width: 619,
    height: 1100,
  },
  {
    src: '/images/realisations/semelle-filante-muret-attentes.webp',
    alt: 'Semelle filante en béton coulée avec attentes pour un muret',
    title: 'Semelle filante d’un muret',
    description: 'Tranchée terrassée puis semelle filante coulée, avec les fers en attente pour l\'élévation du muret.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 825,
    height: 1100,
  },
  {
    src: '/images/realisations/dalle-coffrage-treillis-soude-fouilles.webp',
    alt: 'Préparation d\'une dalle béton : coffrage bois, treillis soudé et fouilles terrassées',
    title: 'Préparation d\'une dalle : coffrage et ferraillage',
    description: 'Terrassement des fouilles, coffrage bois et pose du treillis soudé avant le coulage de la dalle béton.',
    services: ['Terrassement', 'Maçonnerie'],
    width: 1000,
    height: 1335,
  },
  {
    src: '/images/realisations/dalle-beton-coulage-coffrage.webp',
    alt: 'Dalle béton fraîchement coulée et tirée à la règle dans son coffrage bois',
    title: 'Coulage d\'une dalle béton',
    description: 'Coffrage, coulage et réglage d\'une grande dalle béton en extérieur, en prolongement d\'une dalle existante.',
    services: ['Maçonnerie'],
    width: 1152,
    height: 2048,
  },
  {
    src: '/images/realisations/terrasse-entree-dallage-travertin.webp',
    alt: 'Terrasse d\'entrée en dallage travertin avec margelles devant une maison à façade en pierre',
    title: 'Terrasse d\'entrée en travertin',
    description: 'Création d\'un perron maçonné habillé de dalles en travertin, avec margelles et seuil de porte assortis.',
    services: ['Carrelage', 'Maçonnerie'],
    width: 1080,
    height: 810,
  },
  {
    src: '/images/realisations/allee-marches-travertin-jardin.webp',
    alt: 'Allée de jardin courbe et marches en dalles de travertin',
    title: 'Allée et marches en travertin',
    description: 'Allée de jardin aux formes courbes et marches en travertin, posées sur chape pour un rendu durable et élégant.',
    services: ['Carrelage', 'Maçonnerie'],
    width: 1200,
    height: 1600,
  },
  {
    src: '/images/realisations/dalle-terrasse-beton-maison.webp',
    alt: 'Dalle de terrasse en béton coulée à l\'arrière d\'une maison, au niveau de la baie vitrée',
    title: 'Dalle de terrasse en béton',
    description: 'Dalle de terrasse coulée au pied de la maison, bien dressée et de niveau avec le seuil de la baie vitrée.',
    services: ['Maçonnerie'],
    width: 1200,
    height: 800,
  },
]
